[project]
name = "smart-tracker"
version = "0.1.0"
description = "A minimal personal learning tracker with goal-based progress tracking"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.49.1",
    "typer>=0.17.3",
    "pandas>=2.0.0",
]
